### ISSUE TITLE
Getting unknown error when run sass-lint-auto-fix -c filesToLint

### ISSUE THREAD

**Issue by olwen1987** [srowhani/sass-lint-auto-fix#19]
## Problem Description

Getting below error:
/Users/sg0220984/.nvm/versions/node/v8.9.0/lib/node_modules/sass-lint-auto-fix/node_modules/gonzales-pe-sl/lib/gonzales.js:106
            return this.content.some(function (node) {
                                ^

TypeError: this.content.some is not a function
    at Node.contains (/Users/sg0220984/.nvm/versions/node/v8.9.0/lib/node_modules/sass-lint-auto-fix/node_modules/gonzales-pe-sl/lib/gonzales.js:106:26)
    at Node.<anonymous> (/Users/sg0220984/.nvm/versions/node/v8.9.0/lib/node_modules/sass-lint-auto-fix/node_modules/sass-lint/lib/rules/space-before-bang.js:15:38)
    at /Users/sg0220984/.nvm/versions/node/v8.9.0/lib/node_modules/sass-lint-auto-fix/node_modules/gonzales-pe-sl/lib/gonzales.js:314:54
    at Node.traverse (/Users/sg0220984/.nvm/versions/node/v8.9.0/lib/node_modules/sass-lint-auto-fix/node_modules/gonzales-pe-sl/lib/gonzales.js:288:6)
    at Node.traverse (/Users/sg0220984/.nvm/versions/node/v8.9.0/lib/node_modules/sass-lint-auto-fix/node_modules/gonzales-pe-sl/lib/gonzales.js:293:36)
    at Node.traverse (/Users/sg0220984/.nvm/versions/node/v8.9.0/lib/node_modules/sass-lint-auto-fix/node_modules/gonzales-pe-sl/lib/gonzales.js:293:36)
    at Node.traverse (/Users/sg0220984/.nvm/versions/node/v8.9.0/lib/node_modules/sass-lint-auto-fix/node_modules/gonzales-pe-sl/lib/gonzales.js:293:36)
    at Node.traverse (/Users/sg0220984/.nvm/versions/node/v8.9.0/lib/node_modules/sass-lint-auto-fix/node_modules/gonzales-pe-sl/lib/gonzales.js:293:36)
    at Node.traverse (/Users/sg0220984/.nvm/versions/node/v8.9.0/lib/node_modules/sass-lint-auto-fix/node_modules/gonzales-pe-sl/lib/gonzales.js:293:36)
    at Node.traverse (/Users/sg0220984/.nvm/versions/node/v8.9.0/lib/node_modules/sass-lint-auto-fix/node_modules/gonzales-pe-sl/lib/gonzales.js:293:36)

## Screenshot
<img width="1332" alt="screen shot 2018-05-09 at 1 11 31 pm" src="https://user-images.githubusercontent.com/4546860/39831575-8b8c26e0-538a-11e8-90dc-eaab64c3d530.png">

Steps to Recreate
 run sass-lint-auto-fix -c .sass-lint.yml  'app/**/*.scss' -v -q

**Comment by srowhani** [comment]
The -c flag is to pass in configuration. I'll put some time in to improve the docs.

Running `sass-lint-auto-fix -h` will give you a list of available run options. Right now only passing a glob pattern is supported.

Example:
`sass-lint-auto-fix "src/**/*.s+(a|c)ss" -v`
