### ISSUE TITLE
this.content.some is not a function

### ISSUE THREAD

**Issue by whyboris** [srowhani/sass-lint-auto-fix#29]
## Problem Description
I run `sass-lint-auto-fix` (worked about a month ago) on my repository.
Version before and still: `"sass-lint-auto-fix": "0.4.0",`

## Screenshot
```
@fix       Running resolver property-sort-order on src/app/quill/quill-box/quill-box.overrides.scss
@write     Writing resolved tree to src/app/quill/quill-box/quill-box.overrides.scss
/Users/byakubchik/Desktop/bertie/node_modules/gonzales-pe-sl/lib/gonzales.js:106
            return this.content.some(function (node) {
                                ^

TypeError: this.content.some is not a function
    at Node.contains (/Users/byakubchik/Desktop/bertie/node_modules/gonzales-pe-sl/lib/gonzales.js:106:26)
    at Node.<anonymous> (/Users/byakubchik/Desktop/bertie/node_modules/sass-lint/lib/rules/space-before-bang.js:15:38)
    at /Users/byakubchik/Desktop/bertie/node_modules/gonzales-pe-sl/lib/gonzales.js:314:54
    at Node.traverse (/Users/byakubchik/Desktop/bertie/node_modules/gonzales-pe-sl/lib/gonzales.js:288:6)
    at Node.traverse (/Users/byakubchik/Desktop/bertie/node_modules/gonzales-pe-sl/lib/gonzales.js:293:36)
    at Node.traverse (/Users/byakubchik/Desktop/bertie/node_modules/gonzales-pe-sl/lib/gonzales.js:293:36)
    at Node.traverse (/Users/byakubchik/Desktop/bertie/node_modules/gonzales-pe-sl/lib/gonzales.js:293:36)
    at Node.traverse (/Users/byakubchik/Desktop/bertie/node_modules/gonzales-pe-sl/lib/gonzales.js:293:36)
    at Node.traverseByTypes (/Users/byakubchik/Desktop/bertie/node_modules/gonzales-pe-sl/lib/gonzales.js:313:11)
    at Object.detect (/Users/byakubchik/Desktop/bertie/node_modules/sass-lint/lib/rules/space-before-bang.js:13:9)
```
## Steps to recreate

Looks like you'll want some rule that triggers `space-before-bang`

**Comment by whyboris** [comment]
Curiously running the `sass-lint-auto-fix` command a second time didn't generate the error.

**Comment by whyboris** [comment]
*ps* -- after upgrading to `0.10.0` _sass-lint-auto-fix_ does not run -- I get a different error:

```
> publish@0.0.1 scss-lint-fix /Users/byakubchik/Desktop/bertie
> sass-lint-auto-fix --verbose -c src/scss-lint.yml

module.js:538
    throw err;
    ^

Error: Cannot find module 'raven'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/byakubchik/Desktop/bertie/node_modules/sass-lint-auto-fix/dist/index.js:15:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by srowhani** [comment]
This could be resolved by another fix someone put through. Going to close this for now, let me know if you're still experiencing this.
