### ISSUE TITLE
RangeError: Invalid count value

### ISSUE THREAD

**Issue by Johanneke** [srowhani/sass-lint-auto-fix#36]
## Problem Description

When running `npm run sass-lint-auto-fix` I get the following error. My guess is that a check to avoid errors like this is missing.

```
RangeError: Invalid count value
    at String.repeat (native)
    at Logger.pad (/project/node_modules/sass-lint-auto-fix/dist/helpers/logger.js:17:26)
    at Logger.warn (/project/node_modules/sass-lint-auto-fix/dist/helpers/logger.js:43:62)
    at /project/node_modules/sass-lint-auto-fix/dist/sass-lint-auto-fix.js:82:38
    at Array.map (<anonymous>)
    at SlAutoFix.processFile (/project/node_modules/sass-lint-auto-fix/dist/sass-lint-auto-fix.js:59:22)
    at /project/node_modules/sass-lint-auto-fix/dist/sass-lint-auto-fix.js:33:19
    at Array.forEach (<anonymous>)
    at SlAutoFix.run (/project/node_modules/sass-lint-auto-fix/dist/sass-lint-auto-fix.js:31:15)
    at /project/node_modules/sass-lint-auto-fix/dist/index.js:57:21
```

**Comment by Johanneke** [comment]
I'm not very familiar with github, so I don't know the best way to do this, but here is what I think should be changed:

```$ git diff
diff --git a/src/helpers/logger.ts b/src/helpers/logger.ts
index d39d3e8..f2f2410 100644
--- a/src/helpers/logger.ts
+++ b/src/helpers/logger.ts
@@ -24,7 +24,7 @@ export class Logger {
   }
 
   public pad(str: string): string {
-    return str + ' '.repeat(this.padding - str.length);
+    return str + ' '.repeat(Math.max(0, this.padding - str.length));
   }
 
   public verbose(tag: string, ...terms: string[]): void {
```
