### ISSUE TITLE
HTTP error 429

### ISSUE THREAD

**Issue by Johanneke** [srowhani/sass-lint-auto-fix#37]
## Problem Description

After running `npm run sass-lint-auto-fix`, I get a load of http errors. 

```
{ SentryError: HTTP Error (429)
    at new SentryError (/project/node_modules/@sentry/core/dist/error.js:18:28)
    at ClientRequest.<anonymous> (/project/node_modules/@sentry/node/dist/transports/base.js:100:44)
    at Object.onceWrapper (events.js:272:13)
    at ClientRequest.emit (events.js:180:13)
    at ClientRequest.emit (domain.js:421:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:539:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:444:20)
    at TLSSocket.emit (events.js:180:13)
    at TLSSocket.emit (domain.js:421:20) name: 'SentryError' }
```

**Comment by Johanneke** [comment]
After another look at the documentation I saw an `optOut` config for this, so I've enabled that.
